version: '3'
services:
  flasknew:
    build:
      context: .
      dockerfile: Dockerfile-flask
    # environment:
    #   - FLASK_ENV=development
    expose:
      - "5000"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
      restart_policy:
        condition: on-failure

  nginxnew:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flasknew
