# FROM nginx:alpine

# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

FROM public.ecr.aws/nginx/nginx:mainline

COPY nginx/nginx.conf /etc/nginx/nginx.conf
